//Funciones comunes a todo el proyecto


Documentos.labelPlantilla = {
		derecha: "Derecha",	
		izquierda: "Izquierda",	
		superior: "Superior",	
		inferior: "Inferior",		
		tamanio_secciones: "Tama\xF1o de las secciones",	
		conf_tamanio_secciones: "Configura el tama\xF1o de las secciones.",	
		titulo: "Titulo",	
		encabezado: "Encabezado",	
		cuerpo: "Cuerpo",	
		pie_pagina: "Pie de p\xE1gina",
		pie_ultima_pagina: "Pie de ultima p\xE1gina",
		tamanio_pagina: "Tama\xF1o de la p\xE1gina",
		conf_tamanio_pagina: "Configura el tama\xF1o de la p\xE1gina.",
		formato: "Formato",
		personalizado: "Personalizado",
		carta: "Carta",
		legal: "Legal",
		a4: "A4",
		ejecutivo: "Ejecutivo",
		ancho: "Ancho",
		alto: "Alto",
		margenes: "M\xE1rgenes",
		conf_margenes: "Configura las margenes de la plantilla.",
		firma_documento: "Firma documento",
		conf_firma_plantilla: "Configura las firma de la plantilla.",
		conf_firma: "Configurar firma",
		agregar: "Agregar",
		elementos: "Elige los elementos que te gustar\xEDa	a\xF1adir a tu plantilla.",
		texto: "Texto",
		imagen: "Imagen",
		variable: "Variable",
		tabla: "Tabla",
		grupo: "Grupo",
		numero_pagina: "Número de página",
		numero_total_paginas: "N\xFAmero total de p\xE1ginas",
		lista: "Lista",
		configuracion: "Configuraci\xF3n",
		conf_documento: "Configura el documento.",
		consulta_bd: "Consulta Base de Datos",
		margenes_cent: "M\xE1rgenes en cent\xEDmetros",
		tamanio_secciones: "Tama\xF1o de secciones",
		si: "Si",
		no: "No",
		editable: "Editable",
		general: "General",
		conf_general: "Propiedades generales",
		continue_button: "Propiedades generales",
		formatoVariable: "Formato",
		valorDefecto: "Valor defecto",
		tipoVariable: "Tipo variable",
		jerarquiaVariable: "Orden jerárquico",
		editable: "Contenido editable",
		cargo: "Cargo",
		funcionario: "Funcionario",
		tipoFechaReferencia: "Tipo fecha referencia",
		tipoFirmaPlantilla: "Tipo firma plantilla",
		variable: "Variable",
		mostrarNombreFuncionario: "Mostrar nombre funcionario",
		mostrarCargoFuncionario: "Mostrar cargo funcionario",
		decimales: "Decimales",
		longitud: "Longitud",
		editablePlugin: { title: 'Contenido no editable'},
		ordenJerarquico: { organizacion: "Organización",
			plantilla: "Plantilla",
			proceso: "Proceso"},
		presentacionVariable: "Presentación",
		presentacionVariableNumero: "Números",
		presentacionVariableLetras: "Letras",
		valorMoneda: "Valor moneda",
		separadorMiles: "Separador de miles",
		formatoNumerosNegativos: { label: "Formato números negativos",
			signoNegativo: "-1234",
			colorRojo: "1234",
			parentesis: "(1234)",
			parentesisColorRojo: "(1234)"},
		proceso: "Proceso",
		tituloNoEditable:"Titulo no editable",
		tipoLetra: "Tipo de letra",
		mayuscula: "Mayuscula",
		minuscula: "Minuscula",
		tipoImagen: "Tipo imagen",
		firma: "Firma",
		general: "General"	
} ;